### ISSUE TITLE
Add support for missing languages

### ISSUE THREAD

**Issue by andreigec** [KvanTTT/Yandex-Linguistics.NET#19]
I noticed chinese (zh) was missing, and should be added.

**Comment by KvanTTT** [comment]
Where did you find info about **zh**? I [updated](https://github.com/KvanTTT/Yandex-Linguistics.NET/commit/94f677cb933406f61d42ef6ee0d0528adcd82441#diff-ecb3e175750cb684a421c03dfbad6f7e) lang with the latest API changes.
